### ISSUE TITLE
Can I know which algorithm or paper is used for this implementation.

### ISSUE THREAD

**Issue by ajithnaruto** [shagunsodhani/Image-Caption-Generator#2]

**Comment by shagunsodhani** [comment]
Hey @ajithnaruto I did not use any standard paper or algorithm to implement this. This is a simple implementation to demonstrate neural image captioning. Also, from the `README`, 

> Please note that the code in this repo is for use in talks/workshops. There is a lot of room for improvement (in terms of both accuracy and efficiency) so that these aspects can be discussed during the sessions.

> You may refer to Tensorflow's im2text Model for a stable and accurate implementation.
