### ISSUE TITLE
Cannot find debug_image_encoding.pkl

### ISSUE THREAD

**Issue by raghavgurbaxani** [shagunsodhani/Image-Caption-Generator#3]
Hi where can I locate the debug_image_encoding.pkl  which is used in preprocess.py ?

Thanks in advance

**Comment by shagunsodhani** [comment]
Hey @raghavgurbaxani The file is created when we run `preprocess.py`. Let me know if this solves the issue :)

**Comment by raghavgurbaxani** [comment]
Hey @shagunsodhani , I got this  error while running preprocess.py after I ran the VGG16.py.

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Raghav\\Desktop\\Image-Caption-Generator-master master\\data\\model\\debug_image_encoding.pkl'

**Comment by shagunsodhani** [comment]
check if there is a directory called as `model` in `'C:\Users\Raghav\Desktop\Image-Caption-Generator-master master\data\` and create it if it is not there :)

**Comment by raghavgurbaxani** [comment]
Thanks a lot @shagunsodhani

**Comment by shagunsodhani** [comment]
So that works? I would add a fix for it anyways :)

**Comment by raghavgurbaxani** [comment]
Yeah it works, thanks 👍 
Appreciate your quick response

**Comment by NaveenVadavalasa** [comment]
Hey shagun i am getting two errors. please help me.
 i run python3 preprocess.py
error: os error cant find image file
when i run  python3 train.py 
error:file not found error, debug_image_encoding.pkl

please contact on vadavalasan@gmail.com sir.
please help.
Thanks in advance.
Naveen vadavalasa
